server:
  port: 8082

spring:
  application:
    name: goal-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/achievesync_goal_db
    username: achievesync_user
    password: achievesync_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

axon:
  eventhandling:
    processors:
      goal-projection-processor:
        mode: tracking
  serializer:
    general: jackson
    events: jackson
    messages: jackson

grpc:
  server:
    port: 9092

logging:
  level:
    com.achievesync: DEBUG
    org.axonframework: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always